[build-system]
requires = ["hatchling>=1.25", "hatch-vcs>=0.4"]
build-backend = "hatchling.build"

[project]
name = "schemas"
dynamic = ["version"]
description = "Shared Pydantic models for the image_classifier_dojo namespace"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Sidney Batchelder", email = "sbatchelder@whoi.edu" }]
dependencies = [
  "pydantic>=2.11",
]

[project.urls]
Homepage = "https://github.com/WHOIGit/image_classifier_dojo"

[tool.hatch.version]
source = "vcs"

# Build only the schemas package path into the wheel
[tool.hatch.build.targets.wheel]
packages = ["src/dojo/schemas"]

# Keep sdist minimal
[tool.hatch.build.targets.sdist]
include = [
  "pyproject.toml",
  "README.md",
  "src/image_classifier_dojo/schemas/**",
]